name: Export to unitypackage

# JOELwindows7: have write permission pls
permissions:
    contents: write

# use https://github.com/FrostBanditTeam/extract-unity-package-action no it's broken. use Pcy instead!
on: [push, pull_request]

# https://github.com/marketplace/actions/create-unitypackage
jobs:
    bungkus:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            - name: Include which files you wanted to the list file
              run: |
                cd DiceGlow
                pwd
                ls
                echo "Assets/JOELwindows7.meta" > ../metaList
                find Assets/JOELwindows7/ -name \*.meta >> ../metaList
                echo "Now, let's see what do we have here."
                cat ../metaList

            - name: create output directory here
              run: mkdir a

            - name: Wait, check everything first.
              run: |
                pwd
                ls
                echo 'Okay good right?'

            - name: Again, inside DiceGlow.
              run: |
                cd DiceGlow
                pwd
                ls
                echo 'I said in the Asset!'
                cd Assets
                pwd
                ls

            # - name: It's morbin time!
            #   id: extract_unity_package
            #   uses: VRLabs/extract-unity-package-action@v1.2.1
            #   with:
            #     #Specify the unity project path, relative to the repo root.
            #     unityProjectPath: './DiceGlow'
            #     #Optional: Set the directory to package, relative to the project.
            #     packagePath: 'Assets/JOELwindows7'
            #     #Optional: Set the output path for the package.
            #     outputPackagePath: './artifacts/WholeJOELwindows7CVRSets.unitypackage'

            - name: create unitypackage from glob pattern
              id: extract_unity_package
              uses: natsuneko-laboratory/create-unitypackage@v3
              with:
                files-glob: |
                  ./DiceGlow/Assets/JOELwindows7
                dest: WholeJOELwindows7CVRSets.unitypackage
                    
            - name: Here's your morbin sir! Will there be anything else?
              uses: actions/upload-artifact@master
              with:
                path: ${{ steps.extract_unity_package.outputs.artifactsPath }}
                name: Whole_JOELwindows7_CVR-Sets
            - name: HEEEH?!?!?
              run: |
                echo 'hehe 😏';
                echo 'SNAP BACK TO REALITY';